
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action OpenButton;

	private global::Gtk.Action SaveButton;

	private global::Gtk.Action QuitButton;

	private global::Gtk.Action AddFilterButton;

	private global::Gtk.Action ApplyFiltersButton;

	private global::Gtk.Action FilterUpButton;

	private global::Gtk.Action FilterDownButton;

	private global::Gtk.Action DeleteFilterButton;

	private global::Gtk.Action ClearQueueButton;

	private global::Gtk.Fixed MainLayout;

	private global::Gtk.VScrollbar InputScrollY;

	private global::Gtk.HScrollbar InputScrollX;

	private global::Gtk.Image OutputImage;

	private global::Gtk.VScrollbar OutputScrollY;

	private global::Gtk.HScrollbar OutputScrollX;

	private global::Gtk.Toolbar MainToolbar;

	private global::Gtk.Image InputImage;

	private global::Gtk.Label LabelInput;

	private global::Gtk.Label LabelOutput;

	private global::Gtk.ComboBox FilterBox;

	private global::Gtk.Label LabelFilters;

	private global::Gtk.ScrolledWindow FilterDescriptionWindow;

	private global::Gtk.TextView FilterDescription;

	private global::Gtk.Label LabelFilterDescription;

	private global::Gtk.Label LabelParameterName;

	private global::Gtk.ComboBox FilterParameters;

	private global::Gtk.Toolbar FilterToolbar;

	private global::Gtk.ScrolledWindow FilterQueueWindow;

	private global::Gtk.TextView FilterQueueBox;

	private global::Gtk.Label LabelQueue;

	private global::Gtk.Toolbar QueueToolbar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.OpenButton = new global::Gtk.Action("OpenButton", null, global::Mono.Unix.Catalog.GetString("Open Image"), "gtk-open");
		w1.Add(this.OpenButton, null);
		this.SaveButton = new global::Gtk.Action("SaveButton", null, global::Mono.Unix.Catalog.GetString("Save Filtered Image"), "gtk-save");
		w1.Add(this.SaveButton, null);
		this.QuitButton = new global::Gtk.Action("QuitButton", null, global::Mono.Unix.Catalog.GetString("Exit PixelFilter"), "gtk-quit");
		w1.Add(this.QuitButton, null);
		this.AddFilterButton = new global::Gtk.Action("AddFilterButton", null, global::Mono.Unix.Catalog.GetString("Add to Queue"), "gtk-ok");
		w1.Add(this.AddFilterButton, null);
		this.ApplyFiltersButton = new global::Gtk.Action("ApplyFiltersButton", null, global::Mono.Unix.Catalog.GetString("Apply Filters"), "gtk-media-play");
		w1.Add(this.ApplyFiltersButton, null);
		this.FilterUpButton = new global::Gtk.Action("FilterUpButton", null, global::Mono.Unix.Catalog.GetString("Move Filter Up in the Queue"), "gtk-go-up");
		w1.Add(this.FilterUpButton, null);
		this.FilterDownButton = new global::Gtk.Action("FilterDownButton", null, global::Mono.Unix.Catalog.GetString("Move Filter Down in the Queue"), "gtk-go-down");
		w1.Add(this.FilterDownButton, null);
		this.DeleteFilterButton = new global::Gtk.Action("DeleteFilterButton", null, global::Mono.Unix.Catalog.GetString("Remove Filter from the Queue"), "gtk-remove");
		w1.Add(this.DeleteFilterButton, null);
		this.ClearQueueButton = new global::Gtk.Action("ClearQueueButton", null, global::Mono.Unix.Catalog.GetString("Clear Filter Queue"), "gtk-delete");
		w1.Add(this.ClearQueueButton, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.WidthRequest = 750;
		this.HeightRequest = 700;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("PixelFilterMono.PixelFilter64.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		this.DefaultWidth = 750;
		this.DefaultHeight = 700;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainLayout = new global::Gtk.Fixed();
		this.MainLayout.WidthRequest = 750;
		this.MainLayout.HeightRequest = 700;
		this.MainLayout.Name = "MainLayout";
		this.MainLayout.HasWindow = false;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.InputScrollY = new global::Gtk.VScrollbar(null);
		this.InputScrollY.HeightRequest = 256;
		this.InputScrollY.Name = "InputScrollY";
		this.InputScrollY.Adjustment.Upper = 20480D;
		this.InputScrollY.Adjustment.PageIncrement = 1D;
		this.InputScrollY.Adjustment.PageSize = 1D;
		this.InputScrollY.Adjustment.StepIncrement = 1D;
		this.MainLayout.Add(this.InputScrollY);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.InputScrollY]));
		w2.X = 30;
		w2.Y = 100;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.InputScrollX = new global::Gtk.HScrollbar(null);
		this.InputScrollX.WidthRequest = 256;
		this.InputScrollX.Name = "InputScrollX";
		this.InputScrollX.Adjustment.Upper = 20480D;
		this.InputScrollX.Adjustment.PageIncrement = 1D;
		this.InputScrollX.Adjustment.PageSize = 1D;
		this.InputScrollX.Adjustment.StepIncrement = 1D;
		this.MainLayout.Add(this.InputScrollX);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.InputScrollX]));
		w3.X = 70;
		w3.Y = 396;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.OutputImage = new global::Gtk.Image();
		this.OutputImage.WidthRequest = 256;
		this.OutputImage.HeightRequest = 256;
		this.OutputImage.Name = "OutputImage";
		this.MainLayout.Add(this.OutputImage);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.OutputImage]));
		w4.X = 426;
		w4.Y = 100;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.OutputScrollY = new global::Gtk.VScrollbar(null);
		this.OutputScrollY.HeightRequest = 256;
		this.OutputScrollY.Name = "OutputScrollY";
		this.OutputScrollY.Adjustment.Upper = 20480D;
		this.OutputScrollY.Adjustment.PageIncrement = 1D;
		this.OutputScrollY.Adjustment.PageSize = 1D;
		this.OutputScrollY.Adjustment.StepIncrement = 1D;
		this.MainLayout.Add(this.OutputScrollY);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.OutputScrollY]));
		w5.X = 386;
		w5.Y = 100;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.OutputScrollX = new global::Gtk.HScrollbar(null);
		this.OutputScrollX.WidthRequest = 256;
		this.OutputScrollX.Name = "OutputScrollX";
		this.OutputScrollX.Adjustment.Upper = 20480D;
		this.OutputScrollX.Adjustment.PageIncrement = 1D;
		this.OutputScrollX.Adjustment.PageSize = 1D;
		this.OutputScrollX.Adjustment.StepIncrement = 1D;
		this.MainLayout.Add(this.OutputScrollX);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.OutputScrollX]));
		w6.X = 426;
		w6.Y = 396;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'MainToolbar\'><toolitem name=\'OpenButton\' action=\'OpenButton\'/>" +
				"<toolitem name=\'SaveButton\' action=\'SaveButton\'/><toolitem name=\'QuitButton\' act" +
				"ion=\'QuitButton\'/></toolbar></ui>");
		this.MainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/MainToolbar")));
		this.MainToolbar.Name = "MainToolbar";
		this.MainToolbar.ShowArrow = false;
		this.MainToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.MainLayout.Add(this.MainToolbar);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.MainToolbar]));
		w7.X = 70;
		w7.Y = 10;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.InputImage = new global::Gtk.Image();
		this.InputImage.WidthRequest = 256;
		this.InputImage.HeightRequest = 256;
		this.InputImage.Name = "InputImage";
		this.MainLayout.Add(this.InputImage);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.InputImage]));
		w8.X = 70;
		w8.Y = 100;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.LabelInput = new global::Gtk.Label();
		this.LabelInput.Name = "LabelInput";
		this.LabelInput.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Input</b>");
		this.LabelInput.UseMarkup = true;
		this.MainLayout.Add(this.LabelInput);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.LabelInput]));
		w9.X = 70;
		w9.Y = 80;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.LabelOutput = new global::Gtk.Label();
		this.LabelOutput.Name = "LabelOutput";
		this.LabelOutput.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Output</b>");
		this.LabelOutput.UseMarkup = true;
		this.MainLayout.Add(this.LabelOutput);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.LabelOutput]));
		w10.X = 426;
		w10.Y = 80;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.FilterBox = global::Gtk.ComboBox.NewText();
		this.FilterBox.WidthRequest = 220;
		this.FilterBox.Name = "FilterBox";
		this.MainLayout.Add(this.FilterBox);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.FilterBox]));
		w11.X = 70;
		w11.Y = 456;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.LabelFilters = new global::Gtk.Label();
		this.LabelFilters.Name = "LabelFilters";
		this.LabelFilters.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Filters</b>");
		this.LabelFilters.UseMarkup = true;
		this.MainLayout.Add(this.LabelFilters);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.LabelFilters]));
		w12.X = 70;
		w12.Y = 426;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.FilterDescriptionWindow = new global::Gtk.ScrolledWindow();
		this.FilterDescriptionWindow.WidthRequest = 220;
		this.FilterDescriptionWindow.HeightRequest = 70;
		this.FilterDescriptionWindow.Name = "FilterDescriptionWindow";
		this.FilterDescriptionWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child FilterDescriptionWindow.Gtk.Container+ContainerChild
		this.FilterDescription = new global::Gtk.TextView();
		this.FilterDescription.Name = "FilterDescription";
		this.FilterDescription.Editable = false;
		this.FilterDescription.CursorVisible = false;
		this.FilterDescription.AcceptsTab = false;
		this.FilterDescription.WrapMode = ((global::Gtk.WrapMode)(2));
		this.FilterDescriptionWindow.Add(this.FilterDescription);
		this.MainLayout.Add(this.FilterDescriptionWindow);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.FilterDescriptionWindow]));
		w14.X = 70;
		w14.Y = 536;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.LabelFilterDescription = new global::Gtk.Label();
		this.LabelFilterDescription.Name = "LabelFilterDescription";
		this.LabelFilterDescription.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Description</b>");
		this.LabelFilterDescription.UseMarkup = true;
		this.MainLayout.Add(this.LabelFilterDescription);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.LabelFilterDescription]));
		w15.X = 70;
		w15.Y = 506;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.LabelParameterName = new global::Gtk.Label();
		this.LabelParameterName.Name = "LabelParameterName";
		this.LabelParameterName.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Parameter Name</b>");
		this.LabelParameterName.UseMarkup = true;
		this.MainLayout.Add(this.LabelParameterName);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.LabelParameterName]));
		w16.X = 70;
		w16.Y = 620;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.FilterParameters = global::Gtk.ComboBox.NewText();
		this.FilterParameters.WidthRequest = 170;
		this.FilterParameters.Name = "FilterParameters";
		this.MainLayout.Add(this.FilterParameters);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.FilterParameters]));
		w17.X = 70;
		w17.Y = 640;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'FilterToolbar\'><toolitem name=\'AddFilterButton\' action=\'AddFil" +
				"terButton\'/></toolbar></ui>");
		this.FilterToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/FilterToolbar")));
		this.FilterToolbar.Name = "FilterToolbar";
		this.FilterToolbar.ShowArrow = false;
		this.FilterToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.MainLayout.Add(this.FilterToolbar);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.FilterToolbar]));
		w18.X = 250;
		w18.Y = 630;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.FilterQueueWindow = new global::Gtk.ScrolledWindow();
		this.FilterQueueWindow.WidthRequest = 356;
		this.FilterQueueWindow.HeightRequest = 150;
		this.FilterQueueWindow.Name = "FilterQueueWindow";
		this.FilterQueueWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child FilterQueueWindow.Gtk.Container+ContainerChild
		this.FilterQueueBox = new global::Gtk.TextView();
		this.FilterQueueBox.CanFocus = true;
		this.FilterQueueBox.Name = "FilterQueueBox";
		this.FilterQueueBox.Editable = false;
		this.FilterQueueBox.AcceptsTab = false;
		this.FilterQueueWindow.Add(this.FilterQueueBox);
		this.MainLayout.Add(this.FilterQueueWindow);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.FilterQueueWindow]));
		w20.X = 326;
		w20.Y = 456;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.LabelQueue = new global::Gtk.Label();
		this.LabelQueue.Name = "LabelQueue";
		this.LabelQueue.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Queue</b>");
		this.LabelQueue.UseMarkup = true;
		this.MainLayout.Add(this.LabelQueue);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.LabelQueue]));
		w21.X = 326;
		w21.Y = 426;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString(@"<ui><toolbar name='QueueToolbar'><toolitem name='ApplyFiltersButton' action='ApplyFiltersButton'/><toolitem name='FilterUpButton' action='FilterUpButton'/><toolitem name='FilterDownButton' action='FilterDownButton'/><toolitem name='DeleteFilterButton' action='DeleteFilterButton'/><toolitem name='ClearQueueButton' action='ClearQueueButton'/></toolbar></ui>");
		this.QueueToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/QueueToolbar")));
		this.QueueToolbar.Name = "QueueToolbar";
		this.QueueToolbar.ShowArrow = false;
		this.QueueToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.MainLayout.Add(this.QueueToolbar);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.QueueToolbar]));
		w22.X = 326;
		w22.Y = 630;
		this.Add(this.MainLayout);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.OpenButton.Activated += new global::System.EventHandler(this.OnOpenButtonClicked);
		this.SaveButton.Activated += new global::System.EventHandler(this.OnSaveButtonClicked);
		this.QuitButton.Activated += new global::System.EventHandler(this.OnQuitButtonClicked);
		this.AddFilterButton.Activated += new global::System.EventHandler(this.OnAddFilterButtonClicked);
		this.ApplyFiltersButton.Activated += new global::System.EventHandler(this.OnApplyFiltersButtonClicked);
		this.FilterUpButton.Activated += new global::System.EventHandler(this.OnFilterUpButtonClicked);
		this.FilterDownButton.Activated += new global::System.EventHandler(this.OnFilterDownButtonClicked);
		this.DeleteFilterButton.Activated += new global::System.EventHandler(this.OnRemoveFilterButtonClicked);
		this.ClearQueueButton.Activated += new global::System.EventHandler(this.OnClearQueueButtonClicked);
		this.InputScrollY.ValueChanged += new global::System.EventHandler(this.OnInputScrollYValueChanged);
		this.InputScrollX.ValueChanged += new global::System.EventHandler(this.OnInputScrollXValueChanged);
		this.OutputScrollY.ValueChanged += new global::System.EventHandler(this.OnOutputScrollYValueChanged);
		this.OutputScrollX.ValueChanged += new global::System.EventHandler(this.OnOutputScrollXValueChanged);
		this.FilterBox.Changed += new global::System.EventHandler(this.OnFilterBoxChanged);
	}
}
